
name: PROD - CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: creating key ssh server
      env:
        SSH: ${{ secrets.SSH }}
      run: echo "$SSH" >> key
    - name: update permitions
      run: chmod 400 key
    - name: download file
      run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} sh -c 'cd ing2-test-ci && git pull'
    - name: restart services
      run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} sh -c 'systemctl stop flask-server.service && systemctl start flask-server.service'
